# HTTP (RNF-01: también disponible en HTTPS por puerto 3443)
server {
    listen 80;
    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        return 404;
    }
}

# HTTPS con certificado autofirmado (RNF-01)
server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/ssl/clinica.crt;
    ssl_certificate_key /etc/nginx/ssl/clinica.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        return 404;
    }
}
